version: '2'
# 定义四个服务nginx,php,mysql,redis
services:
  nginx:
    # 依赖php服务，意味着在启动nginx之前先启动php
    depends_on:
      - php
      # nginx镜像的路径
    image: nginx:1.12.2
        # 这样使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
    volumes:
      - ~/Projects:/usr/share/nginx/html
      - ~/Documents/docker-lnmp/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/Documents/docker-lnmp/nginx/log/error.log:/var/log/nginx/error.log
        # nginx意外退出时自动重启
    restart: always
        # 映射80和443端口
    ports:
      - "80:80"
      - "443:443"
        # 容器名称
    container_name: nginx
  php:
    depends_on:
      - mysql
      - redis
      - memcached
    build: ./php
    ports:
      - "9001"    
    volumes:
      - ~/Documents/docker-lnmp/php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ~/Documents/docker-lnmp/php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ~/Documents/docker-lnmp/php/php.ini:/usr/local/php/etc/php.ini
      - ~/Documents/docker-lnmp/php/log/php-fpm.log:/usr/local/php/var/log/php-fpm.log
      - ~/Projects:/usr/share/nginx/html
    restart: always
    container_name: php
  # MySQL
  mysql:
    image: mysql:5.6
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ~/Documents/docker-lnmp/mysql/data:/var/lib/mysql
      - ~/Documents/docker-lnmp/mysql/my.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
    #restart: always
    container_name: mysql
  # REDIS
  redis:
    image: redis:3.2.9
    ports:
      - "127.0.0.1:6379:6379"    
    volumes:
      - ~/Documents/docker-lnmp/redis/redis.conf:/usr/local/redis/redis.conf
      - ~/Documents/docker-lnmp/redis/redis.log:/usr/local/redis/redis.log
    restart: always
    container_name: redis
  #elasticsearch
  elasticsearch:
    image: elasticsearch:2.4.5
    ports:
     - "9200:9200"
    volumes: 
     - ~/Documents/docker-lnmp/elasticsearch/data:/usr/local/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    container_name: elasticsearch
  #memcached
  memcached:
    image: memcached:1.5.3
    ports:
     - "11211:11211"
    restart: always
    container_name: memcached
  #php55
  php55:
    depends_on:
      - mysql
      - redis
      - memcached
    build: ./php55
    ports:
      - "9000"  
    volumes:
      - ~/Documents/docker-lnmp/php55/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
      - ~/Documents/docker-lnmp/php55/www.conf:/etc/php5/fpm/pool.d/www.conf
      - ~/Documents/docker-lnmp/php55/php.ini:/etc/php5/fpm/php.ini
      - ~/Documents/docker-lnmp/php55/log/php-fpm.log:/var/log/php5-fpm.log
      - ~/Projects:/usr/share/nginx/html
    #restart: always
    container_name: php55